---
all:
  children:
    keepalived_cluster:
      hosts:
        xubuntu: 
          ansible_host: 192.168.126.137
          ansible_user: jenkins
        comrade2: 
          ansible_host: 192.168.126.134
          ansible_user: comrade2
        comrade3: 
          ansible_host: 192.168.126.135
          ansible_user: comrade3
        comrade4:
          ansible_host: 192.168.126.136
          ansible_user: comrade4
